services:
  fluxerbot:
    build: .
    env_file: .env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml